class BankNames {
  // Keep this FIRST so other patterns can derive from it.
  static final Map<String, String> bankMapping = {
    'HDFCBK': 'HDFC Bank',
    'SBIN': 'State Bank of India',
    'ICICIB': 'ICICI Bank',
    'AXISBK': 'Axis Bank',
    'AXIS': 'Axis Bank',
    'AXISB': 'Axis Bank',
    'KOTAKB': 'Kotak Mahindra Bank',
    'KOTAK': 'Kotak Mahindra Bank',
    'PNB': 'Punjab National Bank',
    'BOB': 'Bank of Baroda',
    'CANBNK': 'Canara Bank',
    'UNIONB': 'Union Bank of India',
    'YESBNK': 'Yes Bank',
    'IDFCBK': 'IDFC First Bank',
    'INDUSB': 'IndusInd Bank',
    'PAYTM': 'Paytm',
    'BHIM': 'BHIM UPI',
    'UPI': 'UPI',
    'GPAY': 'Google Pay',
    'PHONEPE': 'PhonePe',
    'AMZNPY': 'Amazon Pay',
    'SBIINB': 'State Bank of India',
    'PNBSMS': 'Punjab National Bank',
    'IDFCFB': 'IDFC First Bank',
    'BOIIND': 'Bank of India',
    'UNIONS': 'Union Bank',
    'FEDBNK': 'Federal Bank',
    'MAHABK': 'Bank of Maharashtra',
    'CBSSBI': 'SBI CBS',
    'BARBNK': 'Bank of Baroda',
    'UJJIVN': 'Ujjivan Bank',
    'PAYTMB': 'Paytm Payments Bank',
    'AIRTEL': 'Airtel Payments Bank',
    'NSDL': 'NSDL Payments Bank',
    'FINSER': 'Bajaj Finserv',
    'KARBAN': 'Karnataka Bank',
    'DCBBNK': 'DCB Bank',
    'SURYOD': 'Suryoday Bank',
    'RBLBNK': 'RBL Bank',
    'AUFINS': 'AU Small Finance Bank',
    'FINO': 'Fino Payments Bank',
    'CASHP': 'Cashfree',
    'JIOBNK': 'Jio Payments Bank',
    'NBINBK': 'NBFC',
  };
}
